In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import os,sys
sys.path.append(os.path.abspath(os.path.join('..')))

from scripts.utils import *

In [2]:
df = pd.read_csv('.././cleaned_data.csv')

C:\Users\Leul\AppData\Local\Temp\ipykernel_10976\1670631750.py:1: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('.././cleaned_data.csv')

In [3]:
df.head()

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

Accept or reject the following Null Hypotheses:

There are no risk differences across provinces.

There are no risk differences between zip codes.

There are no significant margin (profit) difference between zip codes.

There are not significant risk difference between Women and Men.

### Hypothesis test result

In [4]:
ab_result = result_hypothesis(df)

for test_name, result in ab_result.items():
    print(f'{test_name}')
    print(result)
    print()

Risk Differences Across Provinces
Chi-squared test on Province and TotalPremium: chi2 = 2491500.912683971, p-value = 0.0
Reject the null hypothesis.

Risk Differences Between Postal Codes
Chi-squared test on PostalCode and TotalPremium: chi2 = 224052676.14292973, p-value = 0.0
Reject the null hypothesis.

Margin Differences Between Postal Codes
Z-test on TotalPremium: Z-statistic = -0.4370784074657527, p-value = 0.6620544861020186
Fail to reject the null hypothesis.

Risk Differences Between Women and Men
T-test on TotalPremium: T-statistic = -5.118420932688848, p-value = 3.0925282750010697e-07
Reject the null hypothesis.